### 댓글 등록
POST http://localhost:3000/api/comments
Content-Type: application/json

{
	"nickname": "User1",
	"content": "This is a comment",
	"password": "pass123"
}

### 댓글 목록 조회
GET http://localhost:3000/api/comments?page=1&pageSize=10
Accept: application/json

### 댓글 수정
PUT http://localhost:3000/api/comments/1
Content-Type: application/json

{
	"nickname": "User1",
	"content": "Updated comment",
	"password": "pass123"
}

### 댓글 삭제
DELETE http://localhost:3000/api/comments/1
Content-Type: application/json

{
	"password": "pass123"
}
