### 그룹 등록
POST http://localhost:3000/api/groups
Content-Type: application/json

{
    "name": "코드잇2",
    "password": "abcd1235",
    "imageUrl": "http://example.com/image.jpg",
    "isPublic": true,
    "introduction": "bye"
}

### 그룹 수정
PUT http://localhost:3000/api/groups/414983791
Content-Type: application/json

{
    "name": "코드잇dlfka",
    "password": "abcd1234",
    "imageUrl": "http://example.com/new-image.jpg",
    "isPublic": false,
    "introduction": "수정완료"
}

### 그룹 삭제
DELETE http://localhost:3000/api/groups/414983791
Content-Type: application/json

{
    "password": "abcd1234"
}


### 그룹 목록 조회
GET http://localhost:3000/api/groups?page=1&pageSize=10&sortBy=latest
Accept: application/json

### 그룹 상세 조회
GET http://localhost:3000/api/groups/146310236
Accept: application/json

### 그룹 공감하기
POST http://localhost:3000/api/groups/146310236/like
Content-Type: application/json

### 그룹 조회 권한 확인
POST http://localhost:3000/api/groups/414983791/verify-password
Content-Type: application/json

{
    "password": "abcd1234"
}
